Repository joren-dev/VolkBot, pull requests merged in 2023-02, with the labels that each got.

#2 feat: add initial cog system
  main.py
  src/cogs/ping.py
  src/managers/__init__.py
  src/managers/cog_system.py
  src/managers/discord_client.py
  src/utils/__init__.py
  src/utils/small_utility.py
Labels: enhancement, work in progress

#6 feat: Add cog system
  .env.example
  Pipfile
  Pipfile.lock
  README.md
  main.py
  src/cogs/ping.py
  src/managers/__init__.py
  src/managers/cog_system.py
  src/managers/discord_client.py
  src/utils/__init__.py
  src/utils/small_utility.py
Labels: enhancement

#11 docs: fix broken link in README
  README.md
Labels: bug
